version: '3'

services:
    prod:
      image: trendsearth_api
      environment:
        PORT: 3000
      ports:
        - "3000:3000"
      env_file:
        - prod.env
      volumes:
        - /data/scripts:/data/scripts
      command: start
      depends_on:
        - redis
      deploy:
        restart_policy:
          condition: on-failure

    worker:
      image: trendsearth_api
      env_file:
        - prod.env
      environment:
        PORT: 3000
        FLASK_APP: main.py
      command: worker
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock
        - /data/scripts:/data/scripts
      depends_on:
        - redis
      deploy:
        restart_policy:
          condition: on-failure

    redis:
      image: redis
      deploy:
        restart_policy:
          condition: on-failure
