services:
  manager:
    image: trendsearth-api
    build: .
    command: start
    environment:
      # Pass docker group ID as environment variable for runtime handling
      DOCKER_GROUP_ID: ${DOCKER_GROUP_ID:-999}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    # For Swarm: add capabilities to modify groups at runtime
    cap_add:
      - DAC_OVERRIDE
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          cpus: "0.25"
          memory: 400M

  worker:
    image: trendsearth-api
    build: .
    command: worker
    environment:
      # Pass docker group ID as environment variable for runtime handling
      DOCKER_GROUP_ID: ${DOCKER_GROUP_ID:-999}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    # For Swarm: add capabilities to modify groups at runtime
    cap_add:
      - DAC_OVERRIDE
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          cpus: "0.25"
          memory: 400M
          
  beat:
    image: ${REGISTRY_HOST:-registry.example.com:5000}/trendsearth-api
    build: .
    command: beat
    environment:
      PORT: 3000
      # Pass docker group ID as environment variable for runtime handling
      DOCKER_GROUP_ID: ${DOCKER_GROUP_ID:-999}
    env_file:
      - prod.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    # For Swarm: add capabilities to modify groups at runtime
    cap_add:
      - DAC_OVERRIDE
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          cpus: "0.25"
          memory: 400M

networks:
  backend:
