services:
  admin:
    image: ${REGISTRY_HOST:-registry.example.com:5000}/trendsearth-api
    build: .
    environment:
      PORT: 3000
      FLASK_APP: main.py
    ports:
      - target: 3000
    env_file:
      - prod.env
    command: start
    volumes:
      - ./gefapi:/opt/gef-api/gefapi
      - ./migrations:/opt/gef-api/migrations
      - ./scripts:/opt/gef-api/scripts
