services:
  manager:
    image: trendsearth-api
    build: .
    command: start
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          cpus: "0.25"
          memory: 400M

  worker:
    image: trendsearth-api
    build: .
    command: worker
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          cpus: "0.25"
          memory: 400M
          
  beat:
    image: ${REGISTRY_HOST:-registry.example.com:5000}/trendsearth-api
    build: .
    command: beat
    user: root
    environment:
      PORT: 3000
    env_file:
      - prod.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          cpus: "0.25"
          memory: 400M

networks:
  backend:
