services:
  manager:
    image: trendsearth-api
    build: .
    command: start
    environment:
      GIT_COMMIT_SHA: ${GIT_COMMIT_SHA:-local-dev}
      GIT_BRANCH: ${GIT_BRANCH:-local}
      DEPLOYMENT_ENVIRONMENT: ${DEPLOYMENT_ENVIRONMENT:-development}
    networks:
      - backend
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: 400M

  worker:
    image: trendsearth-api
    build: .
    command: worker
    environment:
      CELERY_WORKER_QUEUES: default
    networks:
      - backend
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: 400M

  builder:
    image: trendsearth-api
    build: .
    command: worker
    user: root
    environment:
      CELERY_WORKER_QUEUES: build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          cpus: "0.25"
          memory: 400M
          
  beat:
    image: ${REGISTRY_HOST:-registry.example.com:5000}/trendsearth-api
    build: .
    command: beat
    environment:
      PORT: 3000
    env_file:
      - prod.env
    networks:
      - backend
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: 400M

networks:
  backend:
