version: "3"

services:
  nginx:
    image: jonasal/nginx-certbot:3.1.2-nginx1.21.6-alpine
    restart: unless-stopped
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx-conf:/etc/nginx/user_conf.d

volumes:
  nginx_secrets:
