prod:
  extends:
    file: base.yml
    service: base
  container_name: gef-api
  ports:
    - "3000:3000"
  env_file:
    - prod.env
  command: start
  restart: always
  links:
    - redis

worker:
  extends:
    file: base.yml
    service: base
  container_name: gef-api-worker
  env_file:
    - prod.env
  environment:
    FLASK_APP: main.py
  command: worker
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  restart: always
  links:
    - redis

redis:
    image: redis
    container_name: gef-api-redis
    ports:
      - 6379
    restart: always
