version: '3.8'

services:
    manager:
      image: trendsearth_api
      environment:
        PORT: 3000
      ports:
        - target: 3000
          published: 3000
          protocol: tcp
          mode: ingress
      env_file:
        - staging.env
      command: start
      networks:
        - backend
        - db
      deploy:
        placement:
          constraints: [node.role == manager]
        restart_policy:
          condition: any
        resources:
          reservations:
            cpus: '0.25'
            memory: 400M

    worker:
      image: trendsearth_api
      env_file:
        - staging.env
      environment:
        PORT: 3000
        FLASK_APP: main.py
      command: worker
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock
      networks:
        - backend
      deploy:
        restart_policy:
          condition: any
        placement:
          constraints: [node.role == manager]
        resources:
          reservations:
            cpus: '0.25'
            memory: 400M

    redis:
      image: redis
      ports:
        - target: 6379
          published: 6379
          protocol: tcp
          mode: ingress
      networks:
        - backend
      deploy:
        placement:
          constraints: [node.role == manager]
        restart_policy:
          condition: any
        resources:
          reservations:
            cpus: '0.25'
            memory: 100M

    database:
      image: postgres:9.6
      environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
        POSTGRES_DB: gef
      volumes:
        - postgres-data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      env_file:
        - staging.env
      networks:
        - db
      deploy:
        restart_policy:
          condition: any

    registry:
      image: registry:2.6.1
      env_file:
        - staging.env
      ports:
        - 5000:5000
      networks:
        - backend
      deploy:
        restart_policy:
          condition: any

volumes:
  postgres-data:

networks:
  backend:
    name: trendsearth_api-backend

  db:
    name: trendsearth_api-db
