version: "3.8"

services:
  manager:
    image: trendsearth-api
    build: .
    environment:
      PORT: 3000
    ports:
      - target: 3000
        published: 3000
    env_file:
      - staging.env
    command: start
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          cpus: "0.25"
          memory: 400M

  worker:
    image: trendsearth-api
    build: .
    env_file:
      - staging.env
    environment:
      PORT: 3000
    command: worker
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          cpus: "0.25"
          memory: 400M

networks:
  backend:
