version: "3"
services:
  nginx:
    image: nginx:1.22.0-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-data/nginx:/etc/nginx/conf.d
      - ./nginx-data/certbot/conf:/etc/letsencrypt
      - ./nginx-data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx-data/certbot/conf:/etc/letsencrypt
      - ./nginx-data/certbot/www:/var/www/certbot
