version: "3.8"

services:
  manager:
    image: 172.40.1.52:5000/trendsearth-api:v2
    environment:
      PORT: 3000
    ports:
      - target: 3000
        published: 3001
    env_file:
      - prod2.env

  worker:
    image: 172.40.1.52:5000/trendsearth-api:v2
    environment:
      PORT: 3000
    env_file:
      - prod2.env

  redis:
    image: redis
    ports:
      - target: 6379
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          cpus: "0.25"
          memory: 100M

networks:
  backend:
