version: "3"

services:
  nginx:
    image: jonasal/nginx-certbot:3.1.2-nginx1.21.6-alpine
    restart: unless-stopped
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx-conf:/etc/nginx/user_conf.d
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          cpus: "0.25"
          memory: 100M

volumes:
  nginx_secrets:
