services:
  nginx:
    image: jonasal/nginx-certbot:5.2.1-nginx1.27.0-alpine
    restart: always
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx-conf:/etc/nginx/user_conf.d
      - status-public:/public
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          cpus: "0.25"
          memory: 100M

volumes:
  nginx_secrets:
  status-public:
    name: "status-public"
