version: '3.8'

services:
    prod:
      image: 172.40.1.52:5000/trendsearth_api
      environment:
        PORT: 3000
      ports:
        - "3000:3000"
      env_file:
        - prod.env
      command: start
      depends_on:
        - redis
      deploy:
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.role == manager]

    worker:
      image: 172.40.1.52:5000/trendsearth_api
      env_file:
        - prod.env
      environment:
        PORT: 3000
        FLASK_APP: main.py
      command: worker
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock
      depends_on:
        - redis
      deploy:
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.role == manager]

    redis:
      image: redis
      ports:
        - "6379:6379"
      deploy:
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.role == manager]
