"""empty message

Revision ID: 06ef5dd6d73a
Revises: e79eaed8af38
Create Date: 2021-12-12 20:19:58.155771

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06ef5dd6d73a'
down_revision = 'e79eaed8af38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'execution',
        sa.Column('is_plugin_execution',
                  sa.Boolean(),
                  nullable=True,
                  server_default=True))
    op.add_column(
        'execution',
        sa.Column('deleted',
                  sa.Boolean(),
                  nullable=False,
                  server_default=False))
    op.alter_column('execution',
                    'user_id',
                    existing_type=postgresql.UUID(),
                    nullable=True,
                    existing_server_default=sa.text(
                        "'8cbf56bc-39db-4c8d-b3ef-b17b23c178e9'::uuid"))
    op.add_column(
        'script',
        sa.Column('cpu_reservation',
                  sa.Integer(),
                  nullable=False,
                  server_default=1e8))
    op.add_column(
        'script',
        sa.Column('cpu_limit',
                  sa.Integer(),
                  nullable=False,
                  server_default=5e8))
    op.add_column(
        'script',
        sa.Column('memory_reservation',
                  sa.Integer(),
                  nullable=False,
                  server_default=1e8))
    op.add_column(
        'script',
        sa.Column('memory_limit',
                  sa.Integer(),
                  nullable=False,
                  server_default=2e9))
    op.add_column(
        'user', sa.Column('first_name', sa.String(length=120), nullable=True))
    op.add_column('user',
                  sa.Column('last_name', sa.String(length=120), nullable=True))
    op.add_column('user',
                  sa.Column('region', sa.String(length=120), nullable=True))
    op.add_column(
        'user',
        sa.Column('is_plugin_user',
                  sa.Boolean(),
                  nullable=False,
                  server_default=True))
    op.add_column(
        'user',
        sa.Column('is_in_mailing_list',
                  sa.Boolean(),
                  nullable=False,
                  server_default=False))
    op.add_column(
        'user',
        sa.Column('deleted',
                  sa.Boolean(),
                  nullable=False,
                  server_default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted')
    op.drop_column('user', 'is_in_mailing_list')
    op.drop_column('user', 'is_plugin_user')
    op.drop_column('user', 'region')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('script', 'memory_limit')
    op.drop_column('script', 'memory_reservation')
    op.drop_column('script', 'cpu_limit')
    op.drop_column('script', 'cpu_reservation')
    op.alter_column('execution',
                    'user_id',
                    existing_type=postgresql.UUID(),
                    nullable=False,
                    existing_server_default=sa.text(
                        "'8cbf56bc-39db-4c8d-b3ef-b17b23c178e9'::uuid"))
    op.drop_column('execution', 'deleted')
    op.drop_column('execution', 'is_plugin_execution')
    # ### end Alembic commands ###
