"""empty message

Revision ID: 115924e98eb5
Revises: e59a6225e14e
Create Date: 2024-08-01 19:08:30.387650

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "115924e98eb5"
down_revision = "e59a6225e14e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("script", sa.Column("environment", sa.Text(), nullable=True))
    op.add_column("script", sa.Column("environment_version", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("script", "environment_version")
    op.drop_column("script", "environment")
    # ### end Alembic commands ###
