"""add user gee credentials

Revision ID: 20250904_add_user_gee_credentials
Revises: 20250903_replace_active_with_pending_tracking
Create Date: 2025-09-04 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_user_gee_credentials'
down_revision = 'replace_active_pending'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gee_oauth_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gee_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gee_service_account_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gee_credentials_type', sa.String(20), nullable=True))
        batch_op.add_column(sa.Column('gee_credentials_created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gee_credentials_created_at')
        batch_op.drop_column('gee_credentials_type')
        batch_op.drop_column('gee_service_account_key')
        batch_op.drop_column('gee_refresh_token')
        batch_op.drop_column('gee_oauth_token')

    # ### end Alembic commands ###