"""add email notifications preference

Revision ID: 20250904_add_email_notifications_preference
Revises: 20250903_replace_active_with_pending_tracking
Create Date: 2025-09-04 23:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250904_add_email_notifications_preference'
down_revision = 'merge_st_be_2025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_notifications_enabled')

    # ### end Alembic commands ###