"""Add build_error column to script table

Revision ID: 3eedf39b54dd
Revises: d0e0fd0030ba
Create Date: 2025-08-14 15:11:15.443219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eedf39b54dd'
down_revision = 'd0e0fd0030ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('script', schema=None) as batch_op:
        batch_op.add_column(sa.Column('build_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('script', schema=None) as batch_op:
        batch_op.drop_column('build_error')

    # ### end Alembic commands ###
