"""empty message

Revision ID: 85176c910eff
Revises: bbfe81ead938
Create Date: 2021-12-08 23:34:31.826981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85176c910eff'
down_revision = 'bbfe81ead938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'region',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'region',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
