"""Remove CPU and memory columns from status_log

Revision ID: 9c02502c27db
Revises: 5937b322a1eb
Create Date: 2025-07-29 15:09:16.299111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c02502c27db'
down_revision = '5937b322a1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_log', schema=None) as batch_op:
        batch_op.drop_column('cpu_usage_percent')
        batch_op.drop_column('memory_available_percent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memory_available_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cpu_usage_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
