"""Add executions_failed and executions_count columns to status_log table

Revision ID: g23bc4de5678
Revises: f12ab3cd4567
Create Date: 2025-01-09 10:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "g23bc4de5678"
down_revision = "f12ab3cd4567"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status_log', sa.Column('executions_failed', sa.Integer(), nullable=True))
    op.add_column('status_log', sa.Column('executions_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status_log', 'executions_count')
    op.drop_column('status_log', 'executions_failed')
    # ### end Alembic commands ###
