"""empty message

Revision ID: bbfe81ead938
Revises: bf6c33480dc6
Create Date: 2021-12-08 23:28:48.470842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbfe81ead938'
down_revision = 'bf6c33480dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('execution', 'is_plugin_execution',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('execution', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'is_plugin_user',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'is_in_mailing_list',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_in_mailing_list',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_plugin_user',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('execution', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('execution', 'is_plugin_execution',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
