"""empty message

Revision ID: bf6c33480dc6
Revises: e79eaed8af38
Create Date: 2021-12-08 12:46:46.271801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf6c33480dc6'
down_revision = 'e79eaed8af38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution', sa.Column('is_plugin_execution', sa.Boolean(), nullable=False))
    op.add_column('execution', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.alter_column('execution', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True,
               existing_server_default=sa.text("'8cbf56bc-39db-4c8d-b3ef-b17b23c178e9'::uuid"))
    op.add_column('user', sa.Column('first_name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('region', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('is_plugin_user', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_in_mailing_list', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted')
    op.drop_column('user', 'is_in_mailing_list')
    op.drop_column('user', 'is_plugin_user')
    op.drop_column('user', 'region')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.alter_column('execution', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False,
               existing_server_default=sa.text("'8cbf56bc-39db-4c8d-b3ef-b17b23c178e9'::uuid"))
    op.drop_column('execution', 'deleted')
    op.drop_column('execution', 'is_plugin_execution')
    # ### end Alembic commands ###
