"""add google groups opt-in

Revision ID: d0e0fd0030ba
Revises: 1f38b2475f49
Create Date: 2025-07-31 18:50:14.220997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e0fd0030ba'
down_revision = '1f38b2475f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_groups_trends_earth_users', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('google_groups_trendsearth', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('google_groups_registration_status', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('google_groups_last_sync', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('google_groups_last_sync')
        batch_op.drop_column('google_groups_registration_status')
        batch_op.drop_column('google_groups_trendsearth')
        batch_op.drop_column('google_groups_trends_earth_users')

    # ### end Alembic commands ###
