"""Add status_log table

Revision ID: f12ab3cd4567
Revises: e79eaed8af38
Create Date: 2025-06-21 16:04:07.000000

"""

import datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f12ab3cd4567"
down_revision = "e79eaed8af38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "status_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("executions_active", sa.Integer(), nullable=True),
        sa.Column("executions_ready", sa.Integer(), nullable=True),
        sa.Column("executions_running", sa.Integer(), nullable=True),
        sa.Column("executions_finished", sa.Integer(), nullable=True),
        sa.Column("users_count", sa.Integer(), nullable=True),
        sa.Column("scripts_count", sa.Integer(), nullable=True),
        sa.Column("memory_available_percent", sa.Float(), nullable=True),
        sa.Column("cpu_usage_percent", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("status_log")
    # ### end Alembic commands ###
