name: Generate API Documentation

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  push:
    branches: [ main, master, staging ]
    paths:
      - 'gefapi/routes/**'
      - 'gefapi/models/**'
      - 'gefapi/services/**'
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --only=main
        
    - name: Generate OpenAPI documentation
      run: |
        mkdir -p gefapi/static
        python generate_swagger.py > gefapi/static/swagger.json
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add gefapi/static/swagger.json
        if git diff --staged --quiet; then
          echo "No changes to swagger.json"
        else
          git commit -m "Auto-update API documentation [skip ci]"
          git push
        fi
