name: Ruff
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Ruff
        run: pip install ruff

      - name: Run linting and formatting checks
        run: |
          ruff check gefapi/ tests/
          ruff format --check gefapi/ tests/
